plugNMeet:
  # Plugnmeet auth information
  host: PLUG_N_MEET_HOSTNAME
  api_key: PLUG_N_MEET_API_KEY
  api_secret: PLUG_N_MEET_SECRET

  # Deletes recording from plugnmeet when recording is ingested
  delete_when_ingested: true

  # Location of recording directory (in this case recordings are located in /opt/plugNMeet-recorder/recording_files directory)
  recording_location: /opt/plugNMeet-recorder
opencast:
  # Opencast auth information
  host: OPENCAST_HOSTNAME
  username: OPENCAST_USERNAME
  password: OPENCAST_PASSWORD

  # Series which will be applied to event
  default_series: PlugNMeet recordings

  # Copies most of the metadata from series rather than predefined metadata below
  copy_metadata_from_series: true

  # Allows event creation even if default_series does not exist
  create_without_series: true

  # Default Access Control List to use for event
  default_acl: public

  # Prefixes the event title with a text for example `PlugNMeet recording {room title}`
  event_title_prefix: PlugNMeet recording

  # Metadata to use when creating opencast event for further info https://docs.opencast.org/r/14.x/developer/#api/events-api/#metadata
  metadata: {
    license: 'ALL RIGHTS RESERVED',
    # This corresponds to Opencast language list entry
    language: 'en',
    publishers: ['PlugNMeet recorder'],
    description: "This is the default description of PlugNMeet recording",
    location: "PlugNMeet conference",
    creators: [ "PlugNMeet" ],
    rights: "",
    contributors: [ ],
    subjects: [ ]
  }

  # Custom ACL configuration that will be ingested with the event for more information https://docs.opencast.org/r/14.x/developer/#api/types/#acl
  custom_acl_config: [
    {
      "action": "write",
      "role": "ROLE_ADMIN"
    },
    {
      "action": "read",
      "role": "ROLE_USER"
    }
  ]
  use_custom_acl_config: true

  # Processing workflow configuration to use when uploading recordings
  # IMPORTANT: Currently it seems opencast has a bug where it doesn't properly parse json values so all configuration params need to be strings
  processing_config: {
    workflow: 'schedule-and-upload',
    configuration: {
      'straightToPublishing': 'true'
    }
  }